//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string BALL_BLOCK_R = "ball_block_r";
        
        public const string CLICK_T5_L = "click_t5_l";
        
        public const string BULLET_HIT_T5_R = "bullet_hit_t5_r";
        
        public const string SLASH_HIT_T4_R = "slash_hit_t4_r";
        
        public const string BULLET_HIT_T2_HEAD = "bullet_hit_t2_head";
        
        public const string KICK_T2_R = "kick_t2_r";
        
        public const string FLYING_T2 = "flying_t2";
        
        public const string FLAME_HIT_T1_HEAD = "flame_hit_t1_head";
        
        public const string SLASH_HIT_T2_HEAD = "slash_hit_t2_head";
        
        public const string SLASH_HIT_T1 = "slash_hit_t1";
        
        public const string RUMBLE_T2 = "rumble_t2";
        
        public const string SLASH_HIT_T3_L = "slash_hit_t3_l";
        
        public const string BODY_SHAKE_T4 = "body_shake_t4";
        
        public const string BULLET_HIT_T2_L = "bullet_hit_t2_l";
        
        public const string RUMBLE_T8 = "rumble_t8";
        
        public const string RECOIL_T6_R_ARMS = "recoil_t6_r_arms";
        
        public const string PINKY_TOUCH_L = "pinky_touch_l";
        
        public const string DRAW_PINWHEEL_T4 = "draw_pinwheel_t4";
        
        public const string SLASH_HIT_T1_R = "slash_hit_t1_r";
        
        public const string CHARGING_T1_L = "charging_t1_l";
        
        public const string DRINKING_T2 = "drinking_t2";
        
        public const string SCAN_L_FEET = "scan_l_feet";
        
        public const string FIST_BUMP_T1_R = "fist_bump_t1_r";
        
        public const string HEARTBEAT_T5 = "heartbeat_t5";
        
        public const string HEAL_T2 = "heal_t2";
        
        public const string ARROW_CHARGING_R_ARMS = "arrow_charging_r_arms";
        
        public const string SLASH_HIT_T7_R = "slash_hit_t7_r";
        
        public const string ARMOR_T3 = "armor_t3";
        
        public const string HIGH_FIVE_T1_R = "high_five_t1_r";
        
        public const string RIDE_HORSE = "ride_horse";
        
        public const string PING_T2_L = "ping_t2_l";
        
        public const string BULLET_HIT_T6_L = "bullet_hit_t6_l";
        
        public const string EXPLOSION_HIT_T2 = "explosion_hit_t2";
        
        public const string FLAME_HIT_T4 = "flame_hit_t4";
        
        public const string WALKING_L = "walking_l";
        
        public const string PING_T1_L = "ping_t1_l";
        
        public const string SLASH_HIT_T4_HEAD = "slash_hit_t4_head";
        
        public const string FALLING_T1 = "falling_t1";
        
        public const string KICK_T3_R = "kick_t3_r";
        
        public const string CLIMBING_T1_R = "climbing_t1_r";
        
        public const string ELECTRIC_L = "electric_l";
        
        public const string CLIMBING_T2_L = "climbing_t2_l";
        
        public const string RECOIL_T1_R_ARMS = "recoil_t1_r_arms";
        
        public const string DRAW_CIRCLE_T1 = "draw_circle_t1";
        
        public const string HIGH_FIVE_R = "high_five_r";
        
        public const string HEAL_T3 = "heal_t3";
        
        public const string ELECTRIC_HIT_T3 = "electric_hit_t3";
        
        public const string RECOIL_T1_L = "recoil_t1_l";
        
        public const string MINE_HIT_T3 = "mine_hit_t3";
        
        public const string ELECTRIC_HIT_T2_L = "electric_hit_t2_l";
        
        public const string MAGIC_CHARGE_L = "magic_charge_l";
        
        public const string RECOIL_T4_L = "recoil_t4_l";
        
        public const string CLICK_T4_L = "click_t4_l";
        
        public const string EXPLOSION_HIT_T2_HEAD = "explosion_hit_t2_head";
        
        public const string ELECTRIC_HIT_T4 = "electric_hit_t4";
        
        public const string RECOIL_T2_R_ARMS = "recoil_t2_r_arms";
        
        public const string EQUIP_SLOT_T1 = "equip_slot_t1";
        
        public const string THUMB_TOUCH_R = "thumb_touch_r";
        
        public const string SCAN_T10 = "scan_t10";
        
        public const string ARMOR_T6 = "armor_t6";
        
        public const string DRAW_PINWHEEL_T1 = "draw_pinwheel_t1";
        
        public const string RECOIL_T3_L = "recoil_t3_l";
        
        public const string ARROW_SHOOTING_L = "arrow_shooting_l";
        
        public const string FIST_BUMP_T3_L = "fist_bump_t3_l";
        
        public const string SLASH_HIT_T6_L = "slash_hit_t6_l";
        
        public const string DASHING_T3 = "dashing_t3";
        
        public const string JUMPING_L = "jumping_l";
        
        public const string RECOIL_T6_L = "recoil_t6_l";
        
        public const string SLASH_HIT_T14 = "slash_hit_t14";
        
        public const string SCAN_R = "scan_r";
        
        public const string EQUIP_SLOT_T5 = "equip_slot_t5";
        
        public const string BODY_SHAKE_T5 = "body_shake_t5";
        
        public const string KICK_T4_L = "kick_t4_l";
        
        public const string EXPLOSION_HIT_T1_R = "explosion_hit_t1_r";
        
        public const string ARMOR_T4 = "armor_t4";
        
        public const string PING_T5_L = "ping_t5_l";
        
        public const string BULLET_HIT_T3_L = "bullet_hit_t3_l";
        
        public const string EQUIP_SLOT_T4 = "equip_slot_t4";
        
        public const string CHARGING_T2_R_ARMS = "charging_t2_r_arms";
        
        public const string SCAN_T4 = "scan_t4";
        
        public const string RECOIL_T6_R = "recoil_t6_r";
        
        public const string MAGIC_SHOOT_R = "magic_shoot_r";
        
        public const string RUMBLE_T1 = "rumble_t1";
        
        public const string ARMOR_T1 = "armor_t1";
        
        public const string CHARGING_T2_R = "charging_t2_r";
        
        public const string RING_TOUCH_R = "ring_touch_r";
        
        public const string FIST_BUMP_T2_L = "fist_bump_t2_l";
        
        public const string PING_T1_R = "ping_t1_r";
        
        public const string RUMBLE_T7 = "rumble_t7";
        
        public const string ARMOR_T2 = "armor_t2";
        
        public const string ARROW_CHARGING_R = "arrow_charging_r";
        
        public const string ELECTRIC_HIT_T2 = "electric_hit_t2";
        
        public const string LANDING = "landing";
        
        public const string CHARGING_T3_L = "charging_t3_l";
        
        public const string PING_T5_R = "ping_t5_r";
        
        public const string FIST_BUMP_T3_R = "fist_bump_t3_r";
        
        public const string CHARGING_T4_R = "charging_t4_r";
        
        public const string SLASH_HIT_T13 = "slash_hit_t13";
        
        public const string PUNCH_T2_R = "punch_t2_r";
        
        public const string BULLET_HIT_T5 = "bullet_hit_t5";
        
        public const string SCAN_T3_L = "scan_t3_l";
        
        public const string RECOIL_T3_L_ARMS = "recoil_t3_l_arms";
        
        public const string ARMOR_T7 = "armor_t7";
        
        public const string BODY_SHAKE_T3 = "body_shake_t3";
        
        public const string RUMBLE_T5 = "rumble_t5";
        
        public const string ARROW_CHARGING_L_ARMS = "arrow_charging_l_arms";
        
        public const string PIERCING_HIT_T4 = "piercing_hit_t4";
        
        public const string FIST_BUMP_T1_L = "fist_bump_t1_l";
        
        public const string KICK_T1_L = "kick_t1_l";
        
        public const string DRAW_CIRCLE_T2 = "draw_circle_t2";
        
        public const string LANDING_L = "landing_l";
        
        public const string PIERCING_HIT_T1 = "piercing_hit_t1";
        
        public const string ARROW_CHARGING_L = "arrow_charging_l";
        
        public const string BULLET_HIT_T1_R = "bullet_hit_t1_r";
        
        public const string EQUIP_SLOT_T2 = "equip_slot_t2";
        
        public const string BODY_SHAKE_T7 = "body_shake_t7";
        
        public const string RECOIL_T2_L_ARMS = "recoil_t2_l_arms";
        
        public const string BULLET_HIT_T4_R = "bullet_hit_t4_r";
        
        public const string ELECTRIC_HIT_T1 = "electric_hit_t1";
        
        public const string SLASH_HIT_T1_L = "slash_hit_t1_l";
        
        public const string HEARTBEAT_T1 = "heartbeat_t1";
        
        public const string FIST_BUMP_T4_L = "fist_bump_t4_l";
        
        public const string CHARGING_T3_R_ARMS = "charging_t3_r_arms";
        
        public const string SHOTGUN_HIT_T3 = "shotgun_hit_t3";
        
        public const string PUNCH_T3_R = "punch_t3_r";
        
        public const string SLASH_HIT_T1_HEAD = "slash_hit_t1_head";
        
        public const string FIST_BUMP_T2_R = "fist_bump_t2_r";
        
        public const string EXPLOSION_HIT_T3 = "explosion_hit_t3";
        
        public const string CLICK_T5_R = "click_t5_r";
        
        public const string PING_T3_R = "ping_t3_r";
        
        public const string CHARGING_T3_R = "charging_t3_r";
        
        public const string SLASH_HIT_T4 = "slash_hit_t4";
        
        public const string SLASH_HIT_T8_R = "slash_hit_t8_r";
        
        public const string EXPLOSION_HIT_T4 = "explosion_hit_t4";
        
        public const string SLASH_HIT_T6 = "slash_hit_t6";
        
        public const string PUNCH_T3_L = "punch_t3_l";
        
        public const string RUMBLE_T3 = "rumble_t3";
        
        public const string EXPLOSION_HIT_T1 = "explosion_hit_t1";
        
        public const string ELECTRIC_HIT_T1_R = "electric_hit_t1_r";
        
        public const string SLASH_HIT_T5_R = "slash_hit_t5_r";
        
        public const string BULLET_HIT_T4_L = "bullet_hit_t4_l";
        
        public const string SLASH_HIT_T7_L = "slash_hit_t7_l";
        
        public const string DASHING_T1 = "dashing_t1";
        
        public const string BULLET_HIT_T6 = "bullet_hit_t6";
        
        public const string ARMOR_T5 = "armor_t5";
        
        public const string PUNCH_T4_R = "punch_t4_r";
        
        public const string CLICK_T3_R = "click_t3_r";
        
        public const string RECOIL_T2_R = "recoil_t2_r";
        
        public const string KNOCK_KNOCK = "knock_knock";
        
        public const string PUNCH_T5_R = "punch_t5_r";
        
        public const string SLASH_HIT_T5 = "slash_hit_t5";
        
        public const string SLASH_HIT_T12 = "slash_hit_t12";
        
        public const string RECOIL_T5_L = "recoil_t5_l";
        
        public const string SCAN_T9 = "scan_t9";
        
        public const string MAGIC_CHARGE_R = "magic_charge_r";
        
        public const string RECOIL_T5_R_ARMS = "recoil_t5_r_arms";
        
        public const string SLASH_HIT_T8 = "slash_hit_t8";
        
        public const string RECOIL_T5_L_ARMS = "recoil_t5_l_arms";
        
        public const string KICK_T2_L = "kick_t2_l";
        
        public const string SLASH_HIT_T6_R = "slash_hit_t6_r";
        
        public const string KICK_T1_R = "kick_t1_r";
        
        public const string SCAN_T7 = "scan_t7";
        
        public const string SLASH_HIT_T2_R = "slash_hit_t2_r";
        
        public const string GRAB_R = "grab_r";
        
        public const string DRAW_PINWHEEL_T2 = "draw_pinwheel_t2";
        
        public const string BULLET_HIT_T7_R = "bullet_hit_t7_r";
        
        public const string SCAN_T3_R = "scan_t3_r";
        
        public const string RECOIL_T5_R = "recoil_t5_r";
        
        public const string ELECTRIC_HIT_T2_R = "electric_hit_t2_r";
        
        public const string SLASH_HIT_T3 = "slash_hit_t3";
        
        public const string RUMBLE_L_FEET = "rumble_l_feet";
        
        public const string BULLET_HIT_T1_L = "bullet_hit_t1_l";
        
        public const string SCAN_T1_L = "scan_t1_l";
        
        public const string EYE_CONTACT = "eye_contact";
        
        public const string CHARGING_T2_L = "charging_t2_l";
        
        public const string DRAW_CROSS_T1 = "draw_cross_t1";
        
        public const string SCAN_T6 = "scan_t6";
        
        public const string KICK_T4_R = "kick_t4_r";
        
        public const string HEAL_T4 = "heal_t4";
        
        public const string BULLET_HIT_T3_HEAD = "bullet_hit_t3_head";
        
        public const string THUMB_TOUCH_L = "thumb_touch_l";
        
        public const string PING_T2_R = "ping_t2_r";
        
        public const string ELECTRIC_R = "electric_r";
        
        public const string HIGH_FIVE_T1_L = "high_five_t1_l";
        
        public const string DASHING_T2 = "dashing_t2";
        
        public const string PING_T4_L = "ping_t4_l";
        
        public const string EQUIP_SLOT_T6 = "equip_slot_t6";
        
        public const string ELECTRIC_HIT_T1_HEAD = "electric_hit_t1_head";
        
        public const string RECOIL_T4_R_ARMS = "recoil_t4_r_arms";
        
        public const string CLICK_T2_L = "click_t2_l";
        
        public const string BULLET_HIT_T1 = "bullet_hit_t1";
        
        public const string MIDDLE_TOUCH_R = "middle_touch_r";
        
        public const string EXPLOSION_HIT_T3_HEAD = "explosion_hit_t3_head";
        
        public const string CHARGING_T1_R_ARMS = "charging_t1_r_arms";
        
        public const string RECOIL_T1_L_ARMS = "recoil_t1_l_arms";
        
        public const string HIGH_FIVE_L = "high_five_l";
        
        public const string CHARGING_T1_L_ARMS = "charging_t1_l_arms";
        
        public const string BLOCKSIGHT = "blocksight";
        
        public const string MIDDLE_TOUCH_L = "middle_touch_l";
        
        public const string PUNCH_T4_L = "punch_t4_l";
        
        public const string FIST_BUMP_T4_R = "fist_bump_t4_r";
        
        public const string CLICK_T3_L = "click_t3_l";
        
        public const string BULLET_HIT_T2 = "bullet_hit_t2";
        
        public const string FLAME_HIT_T1_R = "flame_hit_t1_r";
        
        public const string RUMBLE_R_FEET = "rumble_r_feet";
        
        public const string SCAN_T2_R = "scan_t2_r";
        
        public const string SCANNING_R = "scanning_r";
        
        public const string EXPLOSION_HIT_T5 = "explosion_hit_t5";
        
        public const string SLASH_HIT_T7 = "slash_hit_t7";
        
        public const string CHARGING_T4_L = "charging_t4_l";
        
        public const string PUNCH_T1_L = "punch_t1_l";
        
        public const string CLIMBING_T3_L = "climbing_t3_l";
        
        public const string SCANNING_L = "scanning_l";
        
        public const string PING_T3_L = "ping_t3_l";
        
        public const string RIGHT_GLOVE = "right_glove";
        
        public const string SLASH_HIT_T10 = "slash_hit_t10";
        
        public const string CLICK_T1_R = "click_t1_r";
        
        public const string RECOIL_T6_L_ARMS = "recoil_t6_l_arms";
        
        public const string SCAN_T2_L = "scan_t2_l";
        
        public const string BODY_SHAKE_T2 = "body_shake_t2";
        
        public const string SLASH_HIT_T3_HEAD = "slash_hit_t3_head";
        
        public const string RECOIL_T4_R = "recoil_t4_r";
        
        public const string MINE_HIT_T2 = "mine_hit_t2";
        
        public const string KICK_T3_L = "kick_t3_l";
        
        public const string BULLET_HIT_T5_L = "bullet_hit_t5_l";
        
        public const string HEARTBEAT_T3 = "heartbeat_t3";
        
        public const string BULLET_HIT_T2_R = "bullet_hit_t2_r";
        
        public const string BULLET_HIT_T6_R = "bullet_hit_t6_r";
        
        public const string RUMBLE_T6 = "rumble_t6";
        
        public const string WALKING_R = "walking_r";
        
        public const string CLICK_T4_R = "click_t4_r";
        
        public const string DRAW_CROSS_T2 = "draw_cross_t2";
        
        public const string RECOIL_T1_R = "recoil_t1_r";
        
        public const string FLYING_T1 = "flying_t1";
        
        public const string SCAN_T2 = "scan_t2";
        
        public const string HIGH_FIVE_T2_R = "high_five_t2_r";
        
        public const string GRAB_L = "grab_l";
        
        public const string ARROW_PULLING_L = "arrow_pulling_l";
        
        public const string ELECTRIC_HIT_T1_L = "electric_hit_t1_l";
        
        public const string SHOTGUN_HIT_T2 = "shotgun_hit_t2";
        
        public const string PING_T4_R = "ping_t4_r";
        
        public const string FALLING_T2 = "falling_t2";
        
        public const string SLASH_HIT_T5_HEAD = "slash_hit_t5_head";
        
        public const string ARROW_PULLING_R = "arrow_pulling_r";
        
        public const string HEARTBEAT_T4 = "heartbeat_t4";
        
        public const string SLASH_HIT_T9 = "slash_hit_t9";
        
        public const string SCAN_T2_HEAD = "scan_t2_head";
        
        public const string SLASH_HIT_T2_L = "slash_hit_t2_l";
        
        public const string INDEX_TOUCH_L = "index_touch_l";
        
        public const string RUMBLE_T9 = "rumble_t9";
        
        public const string SLASH_HIT_T5_L = "slash_hit_t5_l";
        
        public const string PUNCH_T2_L = "punch_t2_l";
        
        public const string ELECTRIC_SHORT_R = "electric_short_r";
        
        public const string HEAL_T5 = "heal_t5";
        
        public const string HIGH_FIVE_T2_L = "high_five_t2_l";
        
        public const string BULLET_HIT_T7 = "bullet_hit_t7";
        
        public const string SCAN_T1_R = "scan_t1_r";
        
        public const string HEARTBEAT_T6 = "heartbeat_t6";
        
        public const string PUNCH_T1_R = "punch_t1_r";
        
        public const string SCAN_T1 = "scan_t1";
        
        public const string ELECTRIC_HIT_T2_HEAD = "electric_hit_t2_head";
        
        public const string FLAME_HIT_T2_HEAD = "flame_hit_t2_head";
        
        public const string SHOTGUN_HIT_T1 = "shotgun_hit_t1";
        
        public const string HEARTBEAT_T2 = "heartbeat_t2";
        
        public const string CLIMBING_T2_R = "climbing_t2_r";
        
        public const string EXPLOSION_HIT_T6 = "explosion_hit_t6";
        
        public const string SLASH_HIT_T2 = "slash_hit_t2";
        
        public const string ARROW_SHOOTING_R = "arrow_shooting_r";
        
        public const string BULLET_HIT_T7_L = "bullet_hit_t7_l";
        
        public const string CHARGING_T2_L_ARMS = "charging_t2_l_arms";
        
        public const string GAME_START = "game_start";
        
        public const string DRAW_PINWHEEL_T3 = "draw_pinwheel_t3";
        
        public const string SCAN_T3 = "scan_t3";
        
        public const string FALLING_T3 = "falling_t3";
        
        public const string EXPLOSION_HIT_T2_R = "explosion_hit_t2_r";
        
        public const string BULLET_HIT_T3 = "bullet_hit_t3";
        
        public const string SLASH_HIT_T6_HEAD = "slash_hit_t6_head";
        
        public const string BULLET_HIT_T1_HEAD = "bullet_hit_t1_head";
        
        public const string RUNNING_L = "running_l";
        
        public const string FLAME_HIT_T1_L = "flame_hit_t1_l";
        
        public const string RUMBLE_T4 = "rumble_t4";
        
        public const string CLICK_T1_L = "click_t1_l";
        
        public const string LANDING_R = "landing_r";
        
        public const string MINE_HIT_T1 = "mine_hit_t1";
        
        public const string RUMBLE_L = "rumble_l";
        
        public const string SCAN_T8 = "scan_t8";
        
        public const string HEAL_T1 = "heal_t1";
        
        public const string BALL_BLOCK_L = "ball_block_l";
        
        public const string FLAME_HIT_T2_R = "flame_hit_t2_r";
        
        public const string RUNNING_R = "running_r";
        
        public const string ELECTRIC_SHORT_L = "electric_short_l";
        
        public const string BULLET_HIT_T4 = "bullet_hit_t4";
        
        public const string BULLET_HIT_T4_HEAD = "bullet_hit_t4_head";
        
        public const string CLIMBING_T3_R = "climbing_t3_r";
        
        public const string FLAME_HIT_T3 = "flame_hit_t3";
        
        public const string CLICK_T2_R = "click_t2_r";
        
        public const string LEFT_GLOVE = "left_glove";
        
        public const string JUMPING = "jumping";
        
        public const string FLAME_HIT_T2_L = "flame_hit_t2_l";
        
        public const string BODY_SHAKE_T1 = "body_shake_t1";
        
        public const string CHARGING_T3_L_ARMS = "charging_t3_l_arms";
        
        public const string RECOIL_T3_R_ARMS = "recoil_t3_r_arms";
        
        public const string EXPLOSION_HIT_T1_HEAD = "explosion_hit_t1_head";
        
        public const string SLASH_HIT_T11 = "slash_hit_t11";
        
        public const string RUMBLE_R = "rumble_r";
        
        public const string EQUIP_SLOT_T3 = "equip_slot_t3";
        
        public const string SCAN_T5 = "scan_t5";
        
        public const string SCAN_T1_HEAD = "scan_t1_head";
        
        public const string PINKY_TOUCH_R = "pinky_touch_r";
        
        public const string PUNCH_T5_L = "punch_t5_l";
        
        public const string EQUIP_SLOT_T8 = "equip_slot_t8";
        
        public const string SCAN_R_FEET = "scan_r_feet";
        
        public const string JUMPING_R = "jumping_r";
        
        public const string INDEX_TOUCH_R = "index_touch_r";
        
        public const string BULLET_HIT_T3_R = "bullet_hit_t3_r";
        
        public const string DRINKING_T1 = "drinking_t1";
        
        public const string FLAME_HIT_T2 = "flame_hit_t2";
        
        public const string SLASH_HIT_T3_R = "slash_hit_t3_r";
        
        public const string RECOIL_T3_R = "recoil_t3_r";
        
        public const string SLASH_HIT_T4_L = "slash_hit_t4_l";
        
        public const string SCAN_L = "scan_l";
        
        public const string MAGIC_SHOOT_L = "magic_shoot_l";
        
        public const string BODY_SHAKE_T6 = "body_shake_t6";
        
        public const string RING_TOUCH_L = "ring_touch_l";
        
        public const string EQUIP_SLOT_T7 = "equip_slot_t7";
        
        public const string CHARGING_T1_R = "charging_t1_r";
        
        public const string SLASH_HIT_T8_L = "slash_hit_t8_l";
        
        public const string EXPLOSION_HIT_T2_L = "explosion_hit_t2_l";
        
        public const string PIERCING_HIT_T2 = "piercing_hit_t2";
        
        public const string PIERCING_HIT_T3 = "piercing_hit_t3";
        
        public const string CLIMBING_T1_L = "climbing_t1_l";
        
        public const string RECOIL_T2_L = "recoil_t2_l";
        
        public const string EXPLOSION_HIT_T1_L = "explosion_hit_t1_l";
        
        public const string FLAME_HIT_T1 = "flame_hit_t1";
        
        public const string RECOIL_T4_L_ARMS = "recoil_t4_l_arms";
    }
}
